### ISSUE TITLE
Fix GUI on Linux

### ISSUE THREAD

**Issue by fjug** [fjug/MoMA#1]

**Comment by julou** [comment]
by the way, the current jar file cannot (easily) be run on linux. I copy paste here my email on this:

I get the Mip1.java example from gurobi to work on our server by doing the following:

```
CLASSDIR="-classpath $GUROBI_HOME/lib/gurobi.jar:."
JFLAG="-d . $CLASSDIR"

cp $GUROBI_HOME/examples/java/Mip1.java .
javac $JFLAG Mip1.java
java $CLASSDIR: Mip1
```
Unfortunately, adding this classpath to the MoMA command isn’t enough: 

```
[julou@login13 MOMA]$ java -Xmx4000m $CLASSDIR: -jar TIMM_0.9.4.jar /scicore/home/nimwegen/GROUP/MM_Data/MM_DATA_Manuscript/glu_lac_switch/20150703/20150703_pos0/20150703_pos0_preproc_ready_GL07
Exception in thread "main" java.lang.NoClassDefFoundError: gurobi/GRBException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:274)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: gurobi.GRBException
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 3 more
```
As someone from our facility pointed out, the classpath argument is overridden when using a jar:

> "It's also worth noting that when you use the  java -jar command line option to run your Java program as an executable JAR, then the CLASSPATH environment variable will be ignored, and also the -cp and -classpath switches will be ignored. In this case, you can set your Java classpath in the META-INF/MANIFEST.MF file by using the Class-Path attribute. In short Class-path attribute in manifest file overrides classpath specified by -cp, -classpath or CLASSPATH environment variable."

As far as I can tell, your MANIFEST.MF contains only `.` in its class path (might be worth adding $GUROBI_HOME/lib/gurobi.jar provided that it doesn’t hurt on other OS!):
```
(…)
Class-Path: .
Rsrc-Main-Class: com.jug.MotherMachine
Main-Class: org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader
```

**Comment by julou** [comment]
Really?!
This is great news... It means that we can use it on our server without transferring preprocessing data :)
Any way I can download the update already?

Thanks and best,
Thomas

**Comment by fjug** [comment]
Not yet... I try to also make the GUI run smoothly on Windows, then I will bundle a new jar and contact you, ok?

**Comment by julou** [comment]
your choice… if we’re talking days, it’s completely fine.
if we’re talking weeks (and bundling a jar is not several hours of work), it would help to get it in the meantime ;)

**Comment by fjug** [comment]
We talk hours... No worries...
