### ISSUE TITLE
Clearly explain properties and property files

### ISSUE THREAD

**Issue by fjug** [fjug/MoMA#4]

**Comment by erikvannimwegen** [comment]
Explanation:
Given that we are distributing the code now, I think it is almost necessary that there is some documentation on what parameters are in this file, which ones users might want to change, and which ones they should leave alone.

**Comment by fjug** [comment]
I agree, this deserves a wiki page for sure.

**Comment by julou** [comment]
available at https://github.com/fjug/MoMA/wiki/MoMA%20Properties
clear and detailed :)
